// Copyright (C) 2023 Parrot Drones SAS
//
//    Redistribution and use in source and binary forms, with or without
//    modification, are permitted provided that the following conditions
//    are met:
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in
//      the documentation and/or other materials provided with the
//      distribution.
//    * Neither the name of the Parrot Company nor the names
//      of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written
//      permission.
//
//    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
//    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
//    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
//    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
//    PARROT COMPANY BE LIABLE FOR ANY DIRECT, INDIRECT,
//    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
//    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
//    AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//    OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//    SUCH DAMAGE.

import Foundation

/// Countries of the world.
///
/// The raw value contains the 2-letter ISO 3166 alpha-2 code for this country.
public enum Country: String, CaseIterable {
    case andorra = "AD"
    case unitedArabEmirates = "AE"
    case afghanistan = "AF"
    case antiguaBarbuda = "AG"
    case anguilla = "AI"
    case albania = "AL"
    case armenia = "AM"
    case angola = "AO"
    case antarctica = "AQ"
    case argentina = "AR"
    case americanSamoa = "AS"
    case austria = "AT"
    case australia = "AU"
    case aruba = "AW"
    case alandIslands = "AX"
    case azerbaijan = "AZ"
    case bosniaHerzegovina = "BA"
    case barbados = "BB"
    case bangladesh = "BD"
    case belgium = "BE"
    case burkinaFaso = "BF"
    case bulgaria = "BG"
    case bahrain = "BH"
    case burundi = "BI"
    case benin = "BJ"
    case saintBarthelemy = "BL"
    case bermuda = "BM"
    case brunei = "BN"
    case bolivia = "BO"
    case caribbeanNetherlands = "BQ"
    case brazil = "BR"
    case bahamas = "BS"
    case bhutan = "BT"
    case bouvetIsland = "BV"
    case botswana = "BW"
    case belarus = "BY"
    case belize = "BZ"
    case canada = "CA"
    case cocosIslands = "CC"
    case congoDemocraticRepublic = "CD"
    case centralAfricanRepublic = "CF"
    case congo = "CG"
    case switzerland = "CH"
    case coteDIvoire = "CI"
    case cookIslands = "CK"
    case chile = "CL"
    case cameroon = "CM"
    case china = "CN"
    case colombia = "CO"
    case costaRica = "CR"
    case cuba = "CU"
    case capeVerde = "CV"
    case curacao = "CW"
    case christmasIsland = "CX"
    case cyprus = "CY"
    case czechia = "CZ"
    case germany = "DE"
    case djibouti = "DJ"
    case denmark = "DK"
    case dominica = "DM"
    case dominicanRepublic = "DO"
    case algeria = "DZ"
    case ecuador = "EC"
    case estonia = "EE"
    case egypt = "EG"
    case westernSahara = "EH"
    case eritrea = "ER"
    case spain = "ES"
    case ethiopia = "ET"
    case finland = "FI"
    case fiji = "FJ"
    case falklandIslands = "FK"
    case micronesia = "FM"
    case faroeIslands = "FO"
    case france = "FR"
    case gabon = "GA"
    case unitedKingdom = "GB"
    case grenada = "GD"
    case georgia = "GE"
    case frenchGuiana = "GF"
    case guernsey = "GG"
    case ghana = "GH"
    case gibraltar = "GI"
    case greenland = "GL"
    case gambia = "GM"
    case guinea = "GN"
    case guadeloupe = "GP"
    case equatorialGuinea = "GQ"
    case greece = "GR"
    case southGeorgiaSouthSandwichIslands = "GS"
    case guatemala = "GT"
    case guam = "GU"
    case guineaBissau = "GW"
    case guyana = "GY"
    case hongKong = "HK"
    case heardMcdonaldIslands = "HM"
    case honduras = "HN"
    case croatia = "HR"
    case haiti = "HT"
    case hungary = "HU"
    case indonesia = "ID"
    case ireland = "IE"
    case israel = "IL"
    case isleOfMan = "IM"
    case india = "IN"
    case britishIndianOceanTerritory = "IO"
    case iraq = "IQ"
    case iran = "IR"
    case iceland = "IS"
    case italy = "IT"
    case jersey = "JE"
    case jamaica = "JM"
    case jordan = "JO"
    case japan = "JP"
    case kenya = "KE"
    case kyrgyzstan = "KG"
    case cambodia = "KH"
    case kiribati = "KI"
    case comoros = "KM"
    case saintKittsNevis = "KN"
    case northKorea = "KP"
    case southKorea = "KR"
    case kuwait = "KW"
    case caymanIslands = "KY"
    case kazakhstan = "KZ"
    case laos = "LA"
    case lebanon = "LB"
    case saintLucia = "LC"
    case liechtenstein = "LI"
    case sriLanka = "LK"
    case liberia = "LR"
    case lesotho = "LS"
    case lithuania = "LT"
    case luxembourg = "LU"
    case latvia = "LV"
    case libya = "LY"
    case morocco = "MA"
    case monaco = "MC"
    case moldova = "MD"
    case montenegro = "ME"
    case saintMartin = "MF"
    case madagascar = "MG"
    case marshallIslands = "MH"
    case macedonia = "MK"
    case mali = "ML"
    case myanmar = "MM"
    case mongolia = "MN"
    case macao = "MO"
    case northernMarianaIslands = "MP"
    case martinique = "MQ"
    case mauritania = "MR"
    case montserrat = "MS"
    case malta = "MT"
    case mauritius = "MU"
    case maldives = "MV"
    case malawi = "MW"
    case mexico = "MX"
    case malaysia = "MY"
    case mozambique = "MZ"
    case namibia = "NA"
    case newCaledonia = "NC"
    case niger = "NE"
    case norfolkIsland = "NF"
    case nigeria = "NG"
    case nicaragua = "NI"
    case netherlands = "NL"
    case norway = "NO"
    case nepal = "NP"
    case nauru = "NR"
    case niue = "NU"
    case newZealand = "NZ"
    case oman = "OM"
    case panama = "PA"
    case peru = "PE"
    case frenchPolynesia = "PF"
    case papuaNewGuinea = "PG"
    case philippines = "PH"
    case pakistan = "PK"
    case poland = "PL"
    case saintPierreMiquelon = "PM"
    case pitcairnIslands = "PN"
    case puertoRico = "PR"
    case palestinianTerritories = "PS"
    case portugal = "PT"
    case palau = "PW"
    case paraguay = "PY"
    case qatar = "QA"
    case reunion = "RE"
    case romania = "RO"
    case serbia = "RS"
    case russia = "RU"
    case rwanda = "RW"
    case saudiArabia = "SA"
    case solomonIslands = "SB"
    case seychelles = "SC"
    case sudan = "SD"
    case sweden = "SE"
    case singapore = "SG"
    case saintHelena = "SH"
    case slovenia = "SI"
    case svalbardJanMayen = "SJ"
    case slovakia = "SK"
    case sierraLeone = "SL"
    case sanMarino = "SM"
    case senegal = "SN"
    case somalia = "SO"
    case suriname = "SR"
    case southSudan = "SS"
    case saoTomePrincipe = "ST"
    case elSalvador = "SV"
    case sintMaarten = "SX"
    case syria = "SY"
    case swaziland = "SZ"
    case turksCaicosIslands = "TC"
    case chad = "TD"
    case frenchSouthernTerritories = "TF"
    case togo = "TG"
    case thailand = "TH"
    case tajikistan = "TJ"
    case tokelau = "TK"
    case timorLeste = "TL"
    case turkmenistan = "TM"
    case tunisia = "TN"
    case tonga = "TO"
    case turkey = "TR"
    case trinidadTobago = "TT"
    case tuvalu = "TV"
    case taiwan = "TW"
    case tanzania = "TZ"
    case ukraine = "UA"
    case uganda = "UG"
    case unitedStatesOutlyingIslands = "UM"
    case unitedStates = "US"
    case uruguay = "UY"
    case uzbekistan = "UZ"
    case vaticanCity = "VA"
    case saintVincentGrenadines = "VC"
    case venezuela = "VE"
    case britishVirginIslands = "VG"
    case unitedStatesVirginIslands = "VI"
    case vietnam = "VN"
    case vanuatu = "VU"
    case wallisFutuna = "WF"
    case samoa = "WS"
    case yemen = "YE"
    case mayotte = "YT"
    case southAfrica = "ZA"
    case zambia = "ZM"
    case zimbabwe = "ZW"
}
